[package]
name = "SuiTrack"
version = "0.0.2"

[dependencies]
# Assuming the `sui` repository is at the same level as the package parent directory
Sui = { local = "../../sui/crates/sui-framework/" }

[addresses]
suitrack = "0x0"
